name: Run Docker Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run the Docker image
      run: docker run xaverric/xaverric:whatif
